/*
 * mavcrc.h - MAVLink message table (CRC_EXTRA and payload lengths) for recognising MAVLink frames in
 * the relay. The table itself (mavcrc.c) is generated by tools/gen_mavcrc.py. Portable C99.
 */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t id;
    uint8_t  crc_extra;
    uint8_t  min_len;   /**< base payload length: what a MAVLink 1 frame carries */
    uint8_t  max_len;   /**< with extensions: the most a MAVLink 2 frame carries */
} mavcrc_t;

extern const mavcrc_t mavcrc_table[];   /**< sorted by id */
extern const unsigned mavcrc_count;

/** Table entry for a message id, or NULL if the message is unknown. */
static inline const mavcrc_t *mavcrc_find(uint32_t id)
{
    unsigned lo = 0, hi = mavcrc_count;
    while (lo < hi) {
        unsigned mid = (lo + hi) / 2;
        if (mavcrc_table[mid].id < id)
            lo = mid + 1;
        else
            hi = mid;
    }
    return lo < mavcrc_count && mavcrc_table[lo].id == id ? &mavcrc_table[lo] : 0;
}

#ifdef __cplusplus
}
#endif
