#!/usr/bin/env python3
"""Generate the MAVLink message table used by the relay framer to recognise MAVLink frames.

  python tools/gen_mavcrc.py path/to/c_library_v2/all/all.h

Reads MAVLINK_MESSAGE_CRCS ({msgid, crc_extra, min_len, max_len, ...}) from a header of the generated
MAVLink C library and writes firmware/main/mavcrc.c and host/mavcrc_table.py with the same data.
The header used for the committed tables: mavlink/c_library_v2, branch master, all/all.h (all.xml),
fetched 2026-09-25. The MAVLink project makes the generated C library available under the MIT license
(https://mavlink.io/en/#license, checked 2026-09-27).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text = open(sys.argv[1], encoding='utf-8').read()
    m = re.search(r'#define MAVLINK_MESSAGE_CRCS \{(.*?)\}\s*$', text, re.M)
    if not m:
        sys.exit('MAVLINK_MESSAGE_CRCS not found')
    rows = [tuple(int(x) for x in r.split(',')[:4]) for r in re.findall(r'\{([^{}]*)\}', m.group(1))]
    rows.sort()
    ids = [r[0] for r in rows]
    if len(set(ids)) != len(ids):
        sys.exit('duplicate message ids')
    src = '/'.join(os.path.normpath(sys.argv[1]).replace(os.sep, '/').split('/')[-2:])  # e.g. all/all.h

    c = ['/* Generated by tools/gen_mavcrc.py from %s (MAVLINK_MESSAGE_CRCS): do not edit.' % src,
         ' * Data: MAVLink generated C library (github.com/mavlink/c_library_v2), MIT license. */',
         '#include "mavcrc.h"', '',
         'const mavcrc_t mavcrc_table[] = {']
    for i, e, lo, hi in rows:
        c.append('    { %u, %u, %u, %u },' % (i, e, lo, hi))
    c += ['};', '', 'const unsigned mavcrc_count = sizeof mavcrc_table / sizeof mavcrc_table[0];', '']
    with open(os.path.join(ROOT, 'firmware', 'main', 'mavcrc.c'), 'w', newline='\n') as f:
        f.write('\n'.join(c))

    py = ['"""Generated by tools/gen_mavcrc.py from %s: do not edit. msgid -> (crc_extra, min_len, max_len).' % src,
          'Data: MAVLink generated C library (github.com/mavlink/c_library_v2), MIT license."""',
          '', 'TABLE = {']
    for i, e, lo, hi in rows:
        py.append('    %d: (%d, %d, %d),' % (i, e, lo, hi))
    py += ['}', '']
    with open(os.path.join(ROOT, 'host', 'mavcrc_table.py'), 'w', newline='\n') as f:
        f.write('\n'.join(py))
    print('%d messages, ids %d..%d' % (len(rows), ids[0], ids[-1]))


if __name__ == '__main__':
    main()
